- name: Install FTP
  win_feature:
    name: Web-Ftp-Server
    state: present

- name: Create FTP folder
  win_file:
    path: C:\arquivos_ftp
    state: directory

- name: Create FTP site
  win_iis_ftp:
    name: "ftp"
    state: started
    physical_path: C:\arquivos_ftp
    port: 21